import 'dart:convert';
import 'package:bipolarfactory/Model/tabModel.dart';
import 'package:bipolarfactory/Util/util.dart';
import 'package:http/http.dart';

class Network{
  Future <AutogeneratedList> getImages(int i) async {
    var finalURL=Util.getURL(i);
    final response =await get(Uri.encodeFull(finalURL));
    if(response.statusCode==200){
      List l=json.decode(response.body);
      return AutogeneratedList.fromJson(json.decode(response.body));
    }
    else{
      throw Exception("Error in fetching data");
    }
  }
}